"""empty message

Revision ID: 6fbcdf3a6c8c
Revises: c6f31b8a262d
Create Date: 2020-09-20 19:06:27.672325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fbcdf3a6c8c'
down_revision = 'c6f31b8a262d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('info', sa.Column('check_in', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_info_check_in'), 'info', ['check_in'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_info_check_in'), table_name='info')
    op.drop_column('info', 'check_in')
    # ### end Alembic commands ###
