"""empty message

Revision ID: c6f31b8a262d
Revises: 
Create Date: 2020-09-20 17:17:41.114697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6f31b8a262d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('sex', sa.String(length=8), nullable=True),
    sa.Column('job_title', sa.String(length=32), nullable=True),
    sa.Column('work_location_name', sa.String(length=64), nullable=True),
    sa.Column('taxation_num', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_info_id'), 'info', ['id'], unique=False)
    op.create_index(op.f('ix_info_name'), 'info', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_info_name'), table_name='info')
    op.drop_index(op.f('ix_info_id'), table_name='info')
    op.drop_table('info')
    # ### end Alembic commands ###
